{{- if .Values.ingress.dns }}
  {{- $relname := .Release.Name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-redirect
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: https://{{ .Values.ingress.dns }}
spec:
  ingressClassName: "nginx"
  rules:
    - host: {{ .Values.ingress.redirectDns }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-ui
                port:
                  number: 3000
{{- end }}